"""Add Review Model

Revision ID: 7e538269f0d6
Revises: 633ec2398ca4
Create Date: 2024-09-11 19:22:18.096624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e538269f0d6'
down_revision = '633ec2398ca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
